# ~/.tmuxinator/default.yml

name: default
root: ~/

windows:
  - editor:
      layout: 772a,365x88,0,0{182x88,0,0,0,182x88,183,0[182x44,183,0,1,182x43,183,45,2]}
      panes:
        - clear
        - clear
        - clear
